ALTER TABLE `system_config`
  ADD COLUMN `maintenance_mode_enabled` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `maintenance_message` TEXT NULL,
  ADD COLUMN `offline_retention_days` INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN `backup_frequency` VARCHAR(30) NOT NULL DEFAULT 'DAILY',
  ADD COLUMN `conflict_resolution_policy` VARCHAR(50) NOT NULL DEFAULT 'MANUAL_REVIEW',
  ADD COLUMN `production_assistant_message` TEXT NULL,
  ADD COLUMN `finishing_manager_message` TEXT NULL,
  ADD COLUMN `management_message` TEXT NULL,
  ADD COLUMN `failed_login_alert_mode` VARCHAR(30) NOT NULL DEFAULT 'AUDIT_ONLY',
  ADD COLUMN `failed_login_max_attempts` INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN `ot_allow_partial_close` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `ot_allow_close_with_waste` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `ot_allow_forced_close` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `ot_forced_close_requires_reason` BOOLEAN NOT NULL DEFAULT true;
