
export interface OT {
  descripcion: string;
  'Nro. Cotizacion': string;
  'Nro. Ficha': string;
  Pedido: string;
  OT: string;
  'ORDEN COMPRA': string;
  'Razon Social': string;
  Vendedor: string;
  Glosa: string;
  'MLL Pedido': string;
  'FECHA PED': string;
  'FECHA ENT': string;
  'FECHA INGRESO PLANTA'?: string; // New field
  'CANT PED': number | string;
  Und: string;
  Material: string;
  Ancho: string;
  Drawback: string;
  impresion: string;
  merma: string;
  Medida: string;
  Avance: string;
  desarrollo: string;
  sep_avance: string;
  calibre: string;
  num_colum: string;
  adhesivo: string;
  acabado: string;
  troquel: string;
  SentidoFinal: string;
  diametuco: string;
  ObsDes: string;
  ObsCot: string;
  medidavend: string;
  maquina: string;
  anchoEtiq: string;
  ancho_mate: string;
  forma: string;
  tipoimpre1: string;
  dispensado: string;
  cant_etq_xrollohojas: string;
  fechaPrd: string;
  codmaquina: string;
  s_merma: string;
  mtl_sin_merma: string;
  total_mtl: string;
  total_M2: string;
  LARGO: string;
  col_ficha: string;
  prepicado_h: string;
  prepicado_v: string;
  semicorte: string;
  corte_seguridad: string;
  forma_emb: string;
  und_negocio: string;
  Linea_produccion: string;
  p_cant_rollo_ficha: string;
  Estado_pedido: string;
  r_ref_ot: string;
  logo_tuco: string;
  troquel_ficha: string;
  acabado_ficha: string;
  t_acabado: string;
  ta_acabado: string;
  d_max_bob: string;
}
